import type { Metadata } from "next";
import 'react-toastify/dist/ReactToastify.css';
import "./globals.css";
import ToastProvider from "providers/toast";
import { Roboto } from 'next/font/google'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  variable: "--font-roboto",
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ToastProvider>
          {children}
        </ToastProvider>
      </body>
    </html>
  );
}
